name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build --if-present

    - name: Run Tests
      run: npm test

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'resultnode' # Replace with your Azure Web App name
        # slot-name: 'production'   # Replace with your deployment slot, usually 'production' or leave empty
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
